"""user_img

Revision ID: 234667858833
Revises: 9dfa4ead0d68
Create Date: 2020-09-25 12:25:53.691132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '234667858833'
down_revision = '9dfa4ead0d68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    # ### end Alembic commands ###
